(([
    (array_creation_expression)
    (case_statement)
    (class_declaration)
    (for_statement)
    (foreach_statement)
    (function_definition)
    (if_statement)
    (method_declaration)
    (property_declaration)
    (return_statement)
    (switch_statement)
    (while_statement)
] @_start @_end)
(#make-range! "range" @_start @_end))
