(([
    (generic_function)
    (macro_definition)
    (function_item)
    (function_signature_item)
    (struct_item)
    (enum_item)
    (impl_item)
] @_start @_end)
(#make-range! "range" @_start @_end))
