((comment) @_start @_end
     (#make-range! "range" @_start @_end))

(([
    (left_assignment)
    (left_assignment2)
    (equals_assignment)
    (super_assignment)
    (super_right_assignment)
    (right_assignment)
    (call)
    (function_definition)
    (lambda_function)
    (while)
    (if)
    (for)
    (repeat)
    (switch)
    (binary)
    (unary)
    (pipe)
] @_start @_end)
(#make-range! "range" @_start @_end))
