(([
  (at_rule)
  (call_expression)
  (charset_statement)
  (comment)
  (declaration)
  (extend_statement)
  (for_statement)
  (function_statement)
  (import_statement)
  (include_statement)
  (keyframes_statement)
  (media_statement)
  (mixin_statement)
  (placeholder)
  (rule_set)
  (single_line_comment)
] @_start @_end) (#make-range! "range" @_start @_end))

(arguments (_) @_start @_end (#make-range! "range" @_start @_end))
(at_rule (_) @_start @_end (#make-range! "range" @_start @_end))
(block (_) @_start @_end (#make-range! "range" @_start @_end))
(call_expression (_) @_start @_end (#make-range! "range" @_start @_end))
(charset_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(declaration (_) @_start @_end (#make-range! "range" @_start @_end))
(extend_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(for_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(function_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(import_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(include_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(keyframe_block (_) @_start @_end (#make-range! "range" @_start @_end))
(keyframes_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(media_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(mixin_statement (_) @_start @_end (#make-range! "range" @_start @_end))
(parameters (_) @_start @_end (#make-range! "range" @_start @_end))
(placeholder (_) @_start @_end (#make-range! "range" @_start @_end))
(rule_set (_) @_start @_end (#make-range! "range" @_start @_end))
(selectors (_) @_start @_end (#make-range! "range" @_start @_end))
